# ***LABORATORIO 1:***
Data Types and Data Structures

In [ ]:
my_string1 = 'Welcome to'
my_string2 = "QuantConnect"
print(my_string1 + ' ' + my_string2)

Welcome to QuantConnect


In [ ]:
my_string1 = 'Simple'
my_string2 = "    Trial"
print(my_string1 + ' ' + my_string2)

Simple     Trial


In [ ]:
my_int = 10
print(my_int)
print(type(my_int))

10
<class 'int'>


In [ ]:
my_int = 0
print(my_int)
print(type(my_int))

0
<class 'int'>


In [ ]:
my_string = "100"
print(type(my_string))
my_int = int(my_string)
print(type(my_int))
print()
#My example################
my_string = "9"
print(type(my_string))
my_int = int(my_string)
print(type(my_int))

<class 'str'>
<class 'int'>

<class 'str'>
<class 'int'>


In [ ]:
my_float = 1.0
print(type(my_float))
my_int = 1
print(type(my_int))
print()
#My Example########
my_2float = 8.98
print(type(my_2float))
my_2int = 9
print(type(my_2int))

<class 'float'>
<class 'int'>

<class 'float'>
<class 'int'>


In [ ]:
my_string = "100"
my_float = float(my_string)
print(type(my_float))
print()
#My Example###
my_string2 = "0"
my_float2 = float(my_string2)
print(type(my_float2))

<class 'float'>

<class 'float'>


In [ ]:
my_bool = False
print(my_bool)
print(type(my_bool))
print()
#MY EXAMPLE ############
my_bool2 = True
print(my_bool2)
print(type(my_bool2))


False
<class 'bool'>

True
<class 'bool'>


In [ ]:
print("Addition ", 1+1)
print("Subtraction ", 5-2)
print("Multiplication ", 2*3)
print("Division", 10/2)
print("exponent", 2**3)
print()
#MY EXAMPLE#######
print("Addition ", 9+0)
print("Subtraction ", -8-2)
print("Multiplication ", 77*-3)
print("Division", 10/3)
print("exponent", 2**-2)

Addition  2
Subtraction  3
Multiplication  6
Division 5.0
exponent 8

Addition  9
Subtraction  -10
Multiplication  -231
Division 3.3333333333333335
exponent 0.25


In [ ]:
my_list = ['Quant', 'Connect', 1,2,3]
print(my_list)
print()
#MY EXAMPLE#######
my_list2 = ['Bit', False, int(1.0),2.4]
print(my_list2)

['Quant', 'Connect', 1, 2, 3]

['Bit', False, 1, 2.4]


In [ ]:
my_list = ['Quant', 'Connect', 1,2,3]
print(len(my_list))
print(my_list[0])
print(my_list[len(my_list) - 1])
print()
#MY EXAMPLE#######
my_list2 = ['Bit', False, int(1.0),2.4]
print(len(my_list2))
print(my_list2[0])
print(my_list2[len(my_list2) - 1])

5
Quant
3

4
Bit
2.4


In [ ]:
my_list = ['Quant','Connect',1,2,3]
my_list[2] = 'go'
print(my_list)
print()
#MY EXAMPLE#######
my_list2 = ['Bit', False, int(1.0),2.4]
my_list2[len(my_list2)-1] = 'coin'
print(my_list2)

['Quant', 'Connect', 'go', 2, 3]

['Bit', False, 1, 'coin']


In [ ]:
my_list = ['Quant','Connect',1,2,3]
print(my_list[1:3])
print(my_list[1:])
print(my_list[:3])
print()
#MY EXAMPLE#######
my_list2 = ['Bit', False, int(1.0),2.4, 7]
print(my_list2[2:4])
print(my_list2[2:])
print(my_list2[:2])

['Connect', 1]
['Connect', 1, 2, 3]
['Quant', 'Connect', 1]

[1, 2.4]
[1, 2.4, 7]
['Bit', False]


In [ ]:
my_list = ['Hello', 'Quant']
my_list.append('Hello')
print(my_list)
my_list.remove('Hello')
print(my_list)
print()
#MY EXAMPLE#######
my_list2 = []
my_list2.append('3')
print(my_list2)
my_list2.remove("3")
print(my_list2)

['Hello', 'Quant', 'Hello']
['Quant', 'Hello']

['3']
[]


In [ ]:
my_tuple = ('Welcome','to','QuantConnect')
print(my_tuple[1:])
print()
#MY EXAMPLE#######
my_tuple2=(500, False, "åþ", "®©œ", 5, True)
print(my_tuple2[2:])

('to', 'QuantConnect')

('åþ', '®©œ', 5, True)


In [ ]:
stock_list = ['AAPL','GOOG','IBM','AAPL','IBM','FB','F','GOOG']
stock_set = set(stock_list)
print(stock_set)
print()
#MY EXAMPLE#######
stock_list2 = [3.00,3,3.00,3.,'Bitcoin','Satoshi','satoshi']
stock_set2 = set(stock_list2)
print(stock_set2)

{'AAPL', 'F', 'GOOG', 'FB', 'IBM'}

{'Satoshi', 3.0, 'satoshi', 'Bitcoin'}


In [ ]:
my_dic = {'AAPL': 'Apple', 'FB': 'FaceBook', 'GOOG': 'Alphabet'}
print(my_dic['GOOG'])
print()
#MY EXAMPLE#######
my_dicci = {True: False, 4: 'FaceBook', 1.9: [3,5,"Liubliana"]}
print(my_dicci[True])
print(my_dicci[1.9])

Alphabet

False
[3, 5, 'Liubliana']


In [ ]:
my_dic = {'AAPL': 'Apple', 'FB': 'FaceBook', 'GOOG': 'Alphabet'}
my_dic['GOOG'] = 'Alphabet Company'
print(my_dic['GOOG'])
print(my_dic.keys())
print()
#MY EXAMPLE#######
my_dicci = {True: False, 4: 'FaceBook', 1.9: [3,5,"Liubliana"]}
my_dicci[4]=4
print(my_dicci[4])
print(my_dicci.keys())

Alphabet Company
dict_keys(['AAPL', 'FB', 'GOOG'])

4
dict_keys([True, 4, 1.9])


In [ ]:
my_str = 'Welcome to QuantConnect'
print(my_str[8:])
print()
#MY EXAMPLE#######
my_str2 = 'Undermining bitcoins'
print(my_str2[12:15])

to QuantConnect

bit


In [ ]:
print("Counting the number of e's in this sentence".count('e'))
print('The first time e appears in this sentence'.find('e'))
print('all the a in this sentence now becomes e'.replace('a','e'))
print()
#MY EXAMPLE#######
print('I am on a seafood diet. I see food, and I eat it.'.count("2"))
print('I finally realized that people are prisoners of their phones... that is why it is called a "cell" phone.'.find('.'))
print('Light travels faster than sound. This is why some people appear bright until you hear them speak.'.replace('a','4'))

6
2
ell the e in this sentence now becomes e

0
60
Light tr4vels f4ster th4n sound. This is why some people 4ppe4r bright until you he4r them spe4k.


In [ ]:
Time = '2016-04-01 09:43:00'
splited_list = Time.split(' ')
date = splited_list[0]
time = splited_list[1]
print(date, time)
hour = time.split(':')[0]
print(hour)
print()
#MY EXAMPLE#######
string = 'Сблъсък на кланове е най-добрата игра някога.'
splited_list1 = string.split(' ')
first = splited_list1[0]
third = splited_list1[3]
print(first, third)
weirdestWord = string.split(' ')[4]
print(weirdestWord)

2016-04-01 09:43:00
09

Сблъсък е
най-добрата


In [ ]:
my_time = 'Hour: {}, Minute: {}'.format(9, 43)
print(my_time)
print()
#MY EXAMPLE#######
my_time2 = 'Introduction: {}, MEssage: {}'.format(True, ('Welcome','to','QuantConnect'))
print(my_time2)

Hour: 9, Minute: 43

Introduction: True, MEssage: ('Welcome', 'to', 'QuantConnect')


In [ ]:
print ('pi is %f' % 3.14)
print('%s to %s' % ('Welcome', 'QuantConnect'))
print()
#MY EXAMPLE#######
print ('parte entera de pi es %i' % 3.14)
print('%s or %f' % ('', 3.))

pi is 3.140000
Welcome to QuantConnect

parte entera de pi es 3
 or 3.000000


# ***Logical Operations and Loops***

In [ ]:
print (1 == 0)    # 1 equals 0
print (1 == 1)    # 1 equals 1
print (1 != 0)    # 1 is not equal to 0
print (5 >= 5)    # 5 is greater than or equal to 5
print (5 >= 6)    # 5 is greater than or equal to 6
print()
#MY EXAMPLE#######
print(3.0==3)
print(0==3.)
print(87!=87)
print(4<4)
print(-9.2<=-9.3)

False
True
True
True
False

True
False
False
False
False


In [ ]:
print (2 > 1 and 3 > 2)
print (2 > 1 and 3 < 2)
print (2 > 1 or  3 < 2)
print (2 < 1 and 3 < 2)
print()
#MY EXAMPLE#######
print (9 > 7 or 3 <= 5)
print (26 >= 10 and 87 < 9)
print (25 < 17 or  34 > 6)
print (72 > 10 and 90 < 43)

True
False
True
False

True
False
True
False


In [ ]:
print ((3 > 2 or 1 < 3) and (1!=3 and 4>3) and not ( 3 < 2 or 1 < 3 and (1!=3 and 4>3)))
print (3 > 2 or 1 < 3 and (1!=3 and 4>3) and not ( 3 < 2 or 1 < 3 and (1!=3 and 4>3)))
print()
#MY EXAMPLE#######
print ((3 > 2 or 1 < 3) and (1!=3 and 4>3) and ( 3 < 2 and 1 < 3 and (1!=3 and not 4>3)))
print ((3 > 2 or 1 < 3) and (1!=3 and 4>3) and ( 3 < 2 or 1 < 3 and (1!=3 and 4>3)))

False
True

False
True


In [ ]:
i = 0
if i == 0: print ('i == 0 is True')
print()
#MY EXAMPLE#######
j = 2
if j != 1: print ('j == 1 is False')

i == 0 is True

j == 1 is False


In [ ]:
p = 1 > 0
q = 2 > 3
if p and q:
    print ('p and q is true')
elif p and not q:
    print ('q is false')
elif q and not p:
    print ('p is false')
else:
    print ('None of p and q is true')
print()
#MY EXAMPLE#######
a=1
b=1
if(a == 0) and (b == 0):
    print (True)
elif(a == 0) and (b == 1):
    print (False)
elif(a == 1) and (b == 0):
    print (False)
elif(a == 1) and (b == 1):
    print (True)

q is false

True


In [ ]:
i = 0
while i < 5:
    print (i)
    i += 1
print()
#MY EXAMPLE#######
h = 0
while h > -5:
    print (h)
    h -= 1

0
1
2
3
4

0
-1
-2
-3
-4


In [ ]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
selected = ['AAPL','IBM']
new_list = []
for stock in stocks:
    if stock not in selected:
        new_list.append(stock)
print (new_list)
print()
#MY EXAMPLE#######
stock_list2 = [3.00,3,3.0,3.,'Bitcoin','Satoshi','satoshi']
selected2 = [3]
new_list2 = []
for s in stock_list2:
    if s not in selected2:
        new_list2.append(s)
print (new_list2)

['GOOG', 'FB', 'F', 'V', 'G', 'GE']

['Bitcoin', 'Satoshi', 'satoshi']


In [ ]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
for stock in stocks:
    print (stock)
    if stock == 'FB': break
print()
#MY EXAMPLE#######
stock_list2 = [3.00,3,3.0,3.,'Bitcoin','Satoshi','satoshi']
for item in stock_list2:
    print (item)
    if item == 'Satoshi': break

AAPL
GOOG
IBM
FB

3.0
3
3.0
3.0
Bitcoin
Satoshi


In [ ]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
for stock in stocks:
    if stock == 'FB': continue
    print (stock)
print()
#MY EXAMPLE#######
stock_list2 = [3.00,3,3.0,3.,'Bitcoin','Satoshi','satoshi']
for item in stock_list2:
    if item == 'Satoshi': continue
    print (item)
    

AAPL
GOOG
IBM
F
V
G
GE

3.0
3
3.0
3.0
Bitcoin
satoshi


In [ ]:
squares = []
for i in [1,2,3,4,5]:
    squares.append(i**2)
print (squares)
print()
#MY EXAMPLE#######
sqr_root = []
for i in [1,2,3,4,5]:
    sqr_root.append(i**(1/2))
print (sqr_root)

[1, 4, 9, 16, 25]

[1.0, 1.4142135623730951, 1.7320508075688772, 2.0, 2.23606797749979]


In [ ]:
foo = [1,2,3,4,5]
squares = [x**2 for x in foo]
print (squares)
print()
#MY EXAMPLE#######
foo2 = [1,2,3,4,5]
sqr_root2 = [x**(1/2) for x in foo2]
print (sqr_root2)

[1, 4, 9, 16, 25]

[1.0, 1.4142135623730951, 1.7320508075688772, 2.0, 2.23606797749979]


In [ ]:
stocks = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
selected = ['AAPL','IBM']
new_list = [x for x in stocks if x not in selected]
print (new_list)
print()
#MY EXAMPLE#######
stock_list2 = [3.00,3,3.0,3.,'Bitcoin','Satoshi','satoshi']
selected2 = [3]
new_list22 = [x for x in stock_list2 if x not in selected2]
print (new_list22)

['GOOG', 'FB', 'F', 'V', 'G', 'GE']

['Bitcoin', 'Satoshi', 'satoshi']


In [ ]:
print ([(x, y) for x in [1,2,3] for y in [3,1,4] if x != y])
print ([str(x) + ' vs ' + str(y) for x in ['AAPL','GOOG','IBM','FB'] for y in ['F','V','G','GE'] if x != y])
print()
#MY EXAMPLE#######
print ([(x, y) for x in [1,2,3] for y in [3,1,4] if x != y])
print ([str(x) + ' vs ' + str(y) for x in ['AAPL','GOOG','IBM','FB'] for y in ['F','V','G','GE'] if x != y])

[(1, 3), (1, 4), (2, 3), (2, 1), (2, 4), (3, 1), (3, 4)]
['AAPL vs F', 'AAPL vs V', 'AAPL vs G', 'AAPL vs GE', 'GOOG vs F', 'GOOG vs V', 'GOOG vs G', 'GOOG vs GE', 'IBM vs F', 'IBM vs V', 'IBM vs G', 'IBM vs GE', 'FB vs F', 'FB vs V', 'FB vs G', 'FB vs GE']


# ***Functions and Objective-Oriented Programming***

In [ ]:
def product(x,y):
    return x*y
print (product(2,3))
print (product(5,10))
print()
#MY EXAMPLE#######
def suma(x,y):
    return x+y
print (suma(2,3))
print (suma(5,10))

6
50

5
15


In [ ]:
def say_hi():
    print ('Welcome to QuantConnect')
say_hi()
print()
#MY EXAMPLE#######
def say_hallo():
    print ('Hallo')
say_hallo()

Welcome to QuantConnect

Hallo


In [ ]:
print (range(10))
print (range(1, 11))
print (range(1, 11, 2))
print()
#MY EXAMPLE#######
print (range(0))
print (range(1, 2))
print (range(0, 10, 10))

range(0, 10)
range(1, 11)
range(1, 11, 2)

range(0, 0)
range(1, 2)
range(0, 10, 10)


In [ ]:
tickers = ['AAPL', 'GOOGL', 'IBM', 'FB', 'F', 'V', 'G', 'GE']
print ("The number of tickers is {}".format(len(tickers)))
for k in range(len(tickers)):
    print( k + 1, tickers[k])
print()
#MY EXAMPLE#######
actions = [3.00,3,3.0,3.,'Bitcoin','Satoshi','satoshi']
print ("The number of actions is {}".format(len(actions)))
for k in range(len(actions)):
    print( k + 1, actions[k])

The number of tickers is 8
1 AAPL
2 GOOGL
3 IBM
4 FB
5 F
6 V
7 G
8 GE

The number of actions is 7
1 3.0
2 3
3 3.0
4 3.0
5 Bitcoin
6 Satoshi
7 satoshi


In [ ]:
tickers = ['AAPL','GOOG','IBM','FB','F','V', 'G', 'GE']
print(list(map(len,tickers)))
print()
#MY EXAMPLE#######
actions = ['Bitcoin','Satoshi','satoshi']
print(list(map(len,actions)))

[4, 4, 3, 2, 1, 1, 1, 2]

[7, 7, 7]


In [ ]:
print(list(map(lambda x: x**2, range(10))))
print()
#MY EXAMPLE#######
print(list(map(lambda x: x*2, range(10))))


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [ ]:
print(list(map(lambda x, y: x+y, [1,2,3,4,5], [5,4,3,2,1])))
print()
#MY EXAMPLE#######
print(list(map(lambda x, y, z: x+y*z, [1,2,3,4,5], [5,4,3,2,1], [1,2,3,0,0])))

[6, 6, 6, 6, 6]

[6, 10, 12, 4, 5]


In [1]:
print(sorted([5,2,3,4,1]))
print()
#MY EXAMPLE#######
sorted([2.5,-2,1.3,4.02,1])

[1, 2, 3, 4, 5]



[-2, 1, 1.3, 2.5, 4.02]

In [8]:
price_list = [('AAPL', 144.09), ('GOOGL', 911.71), ('MSFT', 69), ('FB', 150), ('WMT', 75.32)]
print(sorted(price_list, key = lambda x: x[1]))
print()
#MY EXAMPLE#######
actions = [('Bitcoin',7),('Satoshi',-3),('xatoshi',0)]
print(sorted(actions, key = lambda x: x[0]))

[('MSFT', 69), ('WMT', 75.32), ('AAPL', 144.09), ('FB', 150), ('GOOGL', 911.71)]

[('Bitcoin', 7), ('Satoshi', -3), ('xatoshi', 0)]


In [12]:
price_list = [('AAPL', 144.09), ('GOOGL', 911.71), ('MSFT', 69), ('FB', 150), ('WMT', 75.32)]
print(sorted(price_list, key = lambda x: x[1], reverse=True))
print()
#MY EXAMPLE#######
actions = [('Bitcoin',7),('Satoshi',-3),('xatoshi',0)]
print(sorted(actions, key = lambda x: x[0], reverse=True))

[('GOOGL', 911.71), ('FB', 150), ('AAPL', 144.09), ('WMT', 75.32), ('MSFT', 69)]

[('xatoshi', 0), ('Satoshi', -3), ('Bitcoin', 7)]


In [15]:
price_list = [('AAPL', 144.09), ('GOOGL', 911.71), ('MSFT', 69), ('FB', 150), ('WMT', 75.32)]
price_list.sort(key = lambda x: x[1])
print (price_list)
print()
#MY EXAMPLE#######
actions = [('Bitcoin',7),('Satoshi',-3),('xatoshi',0)]
actions.sort(key = lambda x: x[0], reverse=True)
print(actions)

[('MSFT', 69), ('WMT', 75.32), ('AAPL', 144.09), ('FB', 150), ('GOOGL', 911.71)]

[('xatoshi', 0), ('Satoshi', -3), ('Bitcoin', 7)]


In [24]:
class Stock:
    def __init__(self, ticker, open, close, volume):
        self.ticker = ticker
        self.open = open
        self.close = close
        self.volume = volume
        self.rate_return = float(close)/open - 1

    def update(self, open, close):
        self.open = open
        self.close = close
        self.rate_return = float(self.close)/self.open - 1

    def print_return(self):
        print (self.rate_return)

apple  = Stock('AAPL', 143.69, 144.09, 20109375)
google = Stock('GOOGL', 898.7, 911.7, 1561616)

print(apple.ticker)
google.print_return()
google.update(912.8,913.4)
google.print_return()
print()
#MY EXAMPLE#######
class cripto:
    def __init__(self, ticker, val_today, val_yesterday, volume):
        self.ticker = ticker
        self.val_today = val_today
        self.val_yesterday = val_yesterday
        self.volume = volume
        self.rate_return = val_today-val_yesterday

    def update(self, val_today, val_yesterday):
        self.val_today= val_today
        self.val_yesterday = val_yesterday
        self.rate_return = val_today-val_yesterday

    def print_return(self):
        print (self.rate_return)

bitcoin  = cripto('BTC', 62776, 61667.3, 20)
ethereum = cripto('ETH', 3803.6, 3852, 156)

print(bitcoin.ticker)
ethereum.print_return()
ethereum.update(912.8,913.4)
bitcoin.print_return()

AAPL
0.014465338822744034
0.0006573181419806673

BTC
-48.40000000000009
1108.699999999997


In [29]:
apple.ceo = 'Tim Cook'
print(apple.ceo)
print()
#MY EXAMPLE#######
bitcoin.potential = 'Very high.'
print(bitcoin.potential)

Tim Cook

Very high.


In [32]:
print(dir(apple))
print()
#MY EXAMPLE#######
dir(bitcoin)

['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'ceo', 'close', 'open', 'print_return', 'rate_return', 'ticker', 'update', 'volume']



['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'potential',
 'print_return',
 'rate_return',
 'ticker',
 'update',
 'val_today',
 'val_yesterday',
 'volume']

In [38]:
class Child(Stock):
    def __init__(self, name):
        self.name = name

aa = Child('AA')
print (aa.name)
aa.update(100, 102)
print (aa.open)
print (aa.close)
print (aa.print_return())
print()
#MY EXAMPLE#######
class cbs(cripto):
    def __init__(self, name):
        self.name = name

ex = cbs('example1')
print (ex.name)
ex.update(98, 1054)
print (ex.val_today)
print (ex.val_yesterday)
print (ex.print_return())

AA
100
102
0.020000000000000018
None

example1
98
1054
-956
None


# **4. NumPy and Basic Pandas**

In [64]:
import numpy as np

price_list = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
price_array = np.array(price_list)
print (price_array, type(price_array))
print()
#MY EXAMPLE#######
price_list2 = [2, 14.83, 83.2, 142, 54.8]
price_array2 = np.array(price_list2)
print (price_array2, type(price_array2))

[143.73 145.83 143.68 144.02 143.5  142.62] <class 'numpy.ndarray'>

[  2.    14.83  83.2  142.    54.8 ] <class 'numpy.ndarray'>


In [59]:
Ar = np.array([[1,3], [2,4]])
print(Ar, type(Ar))
print()
#MY EXAMPLE#######
hn = np.array([[77,8.9], [0,4],[33,10]])
print(hn, type(hn))

[[1 3]
 [2 4]] <class 'numpy.ndarray'>

[[77.   8.9]
 [ 0.   4. ]
 [33.  10. ]] <class 'numpy.ndarray'>


In [60]:
print (Ar.shape)
print()
#MY EXAMPLE#######
print(hn.shape)

(2, 2)

(3, 2)


In [61]:
print (Ar[0])
print (Ar[1])
print()
#MY EXAMPLE#######
print (hn[0][1])
print (hn[1][0])

[1 3]
[2 4]

8.9
0.0


In [62]:
print ('First column:', Ar[:,0])
print ('Second column:', Ar[:,1])
print()
#MY EXAMPLE#######
print ('Second column:', hn[:,1])
print ('first column:', hn[:,0])

First column: [1 2]
Second column: [3 4]

Second column: [ 8.9  4.  10. ]
first column: [77.  0. 33.]


In [65]:
print(np.log(price_array))
print(np.log(price_array2))

[4.96793654 4.98244156 4.9675886  4.96995218 4.96633504 4.96018375]
[0.69314718 2.69665216 4.42124735 4.95582706 4.00369019]


In [68]:
print(np.mean(price_array))
print (np.std(price_array))
print (np.sum(price_array))
print (np.max(price_array))
print()
#MY EXAMPLE#######
print(np.mean(price_array2))
print (np.std(price_array2))
print (np.sum(price_array2))
print (np.max(price_array2))

143.89666666666668
0.9673790478515796
863.38
145.83

59.366
50.38174097825521
296.83
142.0


In [75]:
import pandas as pd
price = [143.73, 145.83, 143.68, 144.02, 143.5, 142.62]
s = pd.Series(price)
print (s)
print()
#MY EXAMPLE#######
precio= [[314,3.3], [[1.8, 3.68], [14.2, 4.5]], 122]
p = pd.Series(precio)
print (p)

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
dtype: float64

0                    [314, 3.3]
1    [[1.8, 3.68], [14.2, 4.5]]
2                           122
dtype: object


In [88]:
s = pd.Series(price, index = ['a', 'b', 'c', 'd', 'e', 'f'])
print(s)
print()
#MY EXAMPLE#######
p = pd.Series(precio, index = [['a',2], True,'11'])
print(p)

a    143.73
b    145.83
c    143.68
d    144.02
e    143.50
f    142.62
dtype: float64

[a, 2]                    [314, 3.3]
True      [[1.8, 3.68], [14.2, 4.5]]
11                               122
dtype: object


In [90]:
s.index = [6,5,4,3,2,1]
print (s)
print()
#MY EXAMPLE#######
p.index = [3,2,1]
print (p)

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64

3                    [314, 3.3]
2    [[1.8, 3.68], [14.2, 4.5]]
1                           122
dtype: object


In [92]:
print (s[1:])
print (s[:-2])
print()
#MY EXAMPLE#######
print (p[1:])
print (p[:-2])

5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
dtype: float64
6    143.73
5    145.83
4    143.68
3    144.02
dtype: float64

2    [[1.8, 3.68], [14.2, 4.5]]
1                           122
dtype: object
3    [314, 3.3]
dtype: object


In [95]:
print (s[4])
s[4] = 0
print (s)
print()
#MY EXAMPLE#######
print (p[2])
p[2] = 0
print (p)

0.0
6    143.73
5    145.83
4      0.00
3    144.02
2    143.50
1    142.62
dtype: float64

[[1.8, 3.68], [14.2, 4.5]]
3    [314, 3.3]
2             0
1           122
dtype: object


In [99]:
s = pd.Series(price, name = 'Apple Prices')
print (s)
print (s.name)
print()
#MY EXAMPLE#######
p = pd.Series(precio, name = 'bµh')
print (p)
print (p.name)

0    143.73
1    145.83
2    143.68
3    144.02
4    143.50
5    142.62
Name: Apple Prices, dtype: float64
Apple Prices

0                    [314, 3.3]
1    [[1.8, 3.68], [14.2, 4.5]]
2                           122
Name: bµh, dtype: object
bµh


In [100]:
print (s.describe())
print()
#MY EXAMPLE#######
print (p.describe())

count      6.000000
mean     143.896667
std        1.059711
min      142.620000
25%      143.545000
50%      143.705000
75%      143.947500
max      145.830000
Name: Apple Prices, dtype: float64

count              3
unique             3
top       [314, 3.3]
freq               1
Name: bµh, dtype: object


In [104]:
time_index = pd.date_range('2017-01-01', periods = len(s), freq = 'D')
print (time_index)
s.index = time_index
print (s)
print()
#MY EXAMPLE#######
time_index2 = pd.date_range('2021-12-31', periods = len(p), freq = 'Y')
print (time_index2)
p.index = time_index2
print (p)

DatetimeIndex(['2017-01-01', '2017-01-02', '2017-01-03', '2017-01-04',
               '2017-01-05', '2017-01-06'],
              dtype='datetime64[ns]', freq='D')
2017-01-01    143.73
2017-01-02    145.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
2017-01-06    142.62
Freq: D, Name: Apple Prices, dtype: float64

DatetimeIndex(['2021-12-31', '2022-12-31', '2023-12-31'], dtype='datetime64[ns]', freq='A-DEC')
2021-12-31                    [314, 3.3]
2022-12-31    [[1.8, 3.68], [14.2, 4.5]]
2023-12-31                           122
Freq: A-DEC, Name: bµh, dtype: object


In [109]:
s.index = [6,5,4,3,2,1]
print (s)
print (s[1])
print()
#MY EXAMPLE#######
p.index = [3,2,1]
print (p)
print (p[2])

6    143.73
5    145.83
4    143.68
3    144.02
2    143.50
1    142.62
Name: Apple Prices, dtype: float64
142.62

3                    [314, 3.3]
2    [[1.8, 3.68], [14.2, 4.5]]
1                           122
Name: bµh, dtype: object
[[1.8, 3.68], [14.2, 4.5]]


In [113]:
print (s.iloc[1])
print()
#MY EXAMPLE#######
print (p.iloc[0])

145.83

[314, 3.3]


In [115]:
s.index = time_index
print (s['2017-01-03'])
print()
#MY EXAMPLE#######
p.index = time_index2
print (p['2023-12-31'])

143.68

122


In [118]:
print (s['2017-01-02':'2017-01-05'])
print()
#MY EXAMPLE#######
print (p['2021-12-31':'2022-12-31'])

2017-01-02    145.83
2017-01-03    143.68
2017-01-04    144.02
2017-01-05    143.50
Freq: D, Name: Apple Prices, dtype: float64

2021-12-31                    [314, 3.3]
2022-12-31    [[1.8, 3.68], [14.2, 4.5]]
Freq: A-DEC, Name: bµh, dtype: object
